LexinCorpApp/Models/Attorneys/Attorney.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations.Schema;

namespace LexincorpApp.Models
{
    public class Attorney
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "El nombre del abogado es requerido")]
        public string Name { get; set; }
        [Required(ErrorMessage = "La fecha de admisión es requerida")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime AdmissionDate { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        public string Alias { get; set; }
        [Required]
        public string IdentificationNumber { get; set; }
        [Required]
        [Phone]
        public string AssignedPhoneNumber { get; set; }
        [Required]
        [Phone]
        public string PersonalPhoneNumber { get; set; }
        [Required]
        public string EmergencyContact { get; set; }
        [Required]
        [Phone]
        public string EmergencyContactPhoneNumber { get; set; }
        [Required]
        public string NotaryCode { get; set; }
        [Required]
        public int DepartmentId { get; set; }
        public virtual Department Department { get; set; }
        public int UserId { get; set; }
        public virtual User User { get; set; }
        [Required(ErrorMessage = "El email es requerido")]
        [EmailAddress(ErrorMessage = "El formato del email es invalido")]
        public string Email { get; set; }
        public decimal VacationCount { get; set; }
        public bool CanApproveVacations { get; set; }
        [NotMapped]
        public decimal AvailableVacationCount { get; set; }
        //New permission fields
        public bool CanAdminDeposits { get; set; } = false;
        public bool CanPreBill { get; set; } = false;
        public bool CanBill { get; set; } = false;
        public bool CanReviewBillDetail { get; set; } = false;

        /*protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {
            Attorney attorney = (Attorney)validationContext.ObjectInstance;
            if(attorney.User.Username.Contains(" "))
            {
                return new ValidationResult(GetErrorMessage());
            }
            return ValidationResult.Success;
        }
        private string GetErrorMessage()
        {
            return $"El nombre de usuario ingresado contiene espacios en blanco, favor revisar.";
        }*/
    }
}

LexinCorpApp/Models/Attorneys/AttorneySelection.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LexincorpApp.Models
{
    public class AttorneySelection
    {
        public int UserId { get; set; }
        public string AttorneyName { get; set; }
    }
}

LexinCorpApp/Models/Attorneys/Department.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace LexincorpApp.Models
{
    public class Department
    {
        public int DepartmentId { get; set; }
        [Required]
        public string Name { get; set; }
        public virtual ICollection<Attorney> Attorneys { get; set; }
    }
}

LexinCorpApp/Models/Attorneys/NewPasswordUser.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace LexincorpApp.Models
{
    public class NewPasswordUser
    {
        [Required(ErrorMessage = "Contraseña actual es requerida")]
        public string oldPassword { get; set; }
        [Required(ErrorMessage = "Contraseña nueva es requerida")]
        public string newPassword { get; set; }
        [Required(ErrorMessage = "Confirmación de nueva contraseña es requerida")]
        public string confirmNewPassword { get; set; }
    }
}

LexinCorpApp/Models/Attorneys/PermissionsEnum.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LexincorpApp.Models
{
    public enum PermissionsEnum
    {
        CanApproveVacations,
        CanAdminDeposits,
        CanPreBill,
        CanBill,
        CanReviewBillDetail
    }
}

LexinCorpApp/Models/Attorneys/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using LexincorpApp.Models.Validators;

namespace LexincorpApp.Models
{
    public class User
    {
        public int Id { get; set; }
        [Required]
        [NoWhiteSpace(ErrorMessage ="El nombre de usuario no puede contener espacios en blanco")]
        public string Username { get; set; }
        public string Password { get; set; }
        [Required]
        public bool IsAdmin { get; set; }
        public virtual Attorney Attorney { get; set; }
        public bool Active { get; set; } = true;
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual ICollection<Package> Packages { get; set; }
        public virtual ICollection<NotificationAnswer> NotificationAnswers { get; set; }
    }
}

LexinCorpApp/Controllers/AttorneyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using LexincorpApp.Models.ViewModels;
using LexincorpApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using LexincorpApp.Infrastructure;
using LexincorpApp.Models.ExternalServices;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace LexincorpApp.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class AttorneyController : Controller
    {
        private readonly IDepartmentRepository _departmentsRepo;
        private readonly IAttorneyRepository _attorneysRepo;
        private readonly IUserRepository _usersRepo;
        private readonly IGuidManager _guidManager;
        private readonly ICryptoManager _cryptoManager;
        private readonly IMailSender _mailSender;
        public int PageSize = 5;
        public AttorneyController(IDepartmentRepository departmentsRepo, IAttorneyRepository attorneysRepo, IUserRepository usersRepo,
            IGuidManager guidManager, ICryptoManager cryptoManager, IMailSender sender)
        {
            this._departmentsRepo = departmentsRepo;
            this._attorneysRepo = attorneysRepo;
            this._usersRepo = usersRepo;
            this._guidManager = guidManager;
            this._cryptoManager = cryptoManager;
            this._mailSender = sender;
        }
        [Authorize]
        public IActionResult Index()
        {
            return View();
        }
        [Authorize]
        public ViewResult New()
        {
            NewAttorneyViewModel viewModel = new NewAttorneyViewModel
            {
                Attorney = new Attorney { User = new User() },
                Departments = _departmentsRepo.Departments.ToList()
            };
            ViewBag.AddedAttorney = TempData["added"];
            return View(viewModel);
        }
        [Authorize]
        [HttpPost]
        public IActionResult New(Attorney attorney)
        {
            if (!_usersRepo.VerifyUsername(attorney.User.Username))
            {
                ModelState.AddModelError("uqUsername", "El usuario ingresado ya existe");
            }
            if (!_attorneysRepo.VerifyEmail(attorney.Email))
            {
                ModelState.AddModelError("uqEmail", "El correo ingresado ya existe");
            }
            if (!_attorneysRepo.VerifyNotaryCode(attorney.NotaryCode))
            {
                ModelState.AddModelError("uqNotaryCode", "El código de notario ingresado ya existe");
            }
            //if(attorney.User.Username.Contains(" "))
            //{
            //    ModelState.AddModelError("whiteSpacesUsername", "El nombre de usuario contiene espacios en blanco, favor no incluir espacios en blanco");
            //}
            if (!ModelState.IsValid)
            {
                NewAttorneyViewModel viewModel = new NewAttorneyViewModel
                {
                    Departments = _departmentsRepo.Departments.ToList()
                };
                viewModel.Attorney = attorney;
                return View(viewModel);
            }
            else
            {
                //string guidGenerated = _guidManager.GenerateGuid();
                //string passwordDefault = guidGenerated.Substring(guidGenerated.Length - 12, 12);
                string passwordOriginal = attorney.User.Password;
                string passwordHashed = _cryptoManager.HashString(attorney.User.Password);
                attorney.User.Password = passwordHashed;
                _attorneysRepo.Save(attorney);
                //Envío de password sin hash al usuario
                string emailBody = $"Se le ha creado un acceso a la aplicación Lexincorp Nicaragua Web, su usuario es {attorney.User.Username} " +
                    $"y su clave de acceso es {passwordOriginal}. \n**Este es un mensaje autogenerado por el sistema, favor no responder**";
                _mailSender.SendMail(attorney.Email, "Usuario web creado para aplicación Lexincorp Nicaragua Web", emailBody);
                TempData["added"] = true;
                return RedirectToAction("New");
            }
        }
        [Authorize]
        public IActionResult Admin(string filter, int pageNumber = 1)
        {

            ViewBag.Updated = TempData["updated"];
            Func<Attorney, bool> filterFunction = c => String.IsNullOrEmpty(filter) || c.Name.CaseInsensitiveContains(filter) || c.IdentificationNumber.CaseInsensitiveContains(filter);
            ViewBag.ResetedPassword = TempData["ResetedPassword"];
            AttorneyListViewModel viewModel = new AttorneyListViewModel();
            viewModel.CurrentFilter = filter;
            viewModel.Attorneys = _attorneysRepo.Attorneys
                .Include(a => a.Department)
                .Include(a => a.User)
                .Where(filterFunction)
                .OrderBy(a => a.Id)
                .Skip((pageNumber - 1) * PageSize)
                .Take(PageSize);
            viewModel.PagingInfo = new PagingInfo
            {
                CurrentPage = pageNumber,
                ItemsPerPage = PageSize,
                TotalItems = _attorneysRepo.Attorneys.Count(filterFunction)
            };
            TempData["filter"] = filter;
            return View(viewModel);
        }
        [Authorize]
        public IActionResult Edit(int id)
        {
            TempData.Keep();
            ViewBag.UpdatedAttorney = TempData["updated"];
            NewAttorneyViewModel viewModel = new NewAttorneyViewModel
            {
                Departments = _departmentsRepo.Departments.ToList()
            };
            viewModel.Attorney = _attorneysRepo.Attorneys.Where(a => a.Id == id).Include(a => a.User).Include(a => a.Department).First();
            if (viewModel.Attorney == null)
            {
                return NotFound();
            }
            return View(viewModel);
        }
        [Authorize]
        [HttpPost]
        public IActionResult Edit(Attorney attorney)
        {
            TempData.Keep();
            if (!_usersRepo.VerifyUsername(attorney.User.Username) && !_usersRepo.VerifyAttorneyIDAndUsername(attorney.Id, attorney.UserId))
            {
                ModelState.AddModelError("uqUsername", "El usuario ingresado ya existe");
            }
            if (!_attorneysRepo.VerifyEmail(attorney.Email) && !_attorneysRepo.VerifyAttorneyIDAndEmailOwnership(attorney.Id, attorney.Email))
            {
                ModelState.AddModelError("uqEmail", "El correo ingresado ya existe");
            }
            if (!_attorneysRepo.VerifyNotaryCode(attorney.NotaryCode) && !_attorneysRepo.verifyAttorneyIDAndNotaryCodeOwnership(attorney.Id, attorney.NotaryCode))
            {
                ModelState.AddModelError("uqNotaryCode", "El código de notario ingresado ya existe");
            }
            if (!ModelState.IsValid)
            {
                NewAttorneyViewModel viewModel = new NewAttorneyViewModel
                {
                    Departments = _departmentsRepo.Departments.ToList()
                };
                viewModel.Attorney = attorney;
                return View(viewModel);
            }
            else
            {
                bool passwordModified = false;
                if(attorney.User.Password != null && (attorney.User.Password != " " || attorney.User.Password != ""))
                {
                    passwordModified = true;
                    string passwordOriginal = attorney.User.Password;
                    string passwordHashed = _cryptoManager.HashString(attorney.User.Password);
                    attorney.User.Password = passwordHashed;
                }
                _attorneysRepo.Save(attorney, passwordModified);
                _usersRepo.Save(attorney.User);
                TempData["updated"] = true;
                return RedirectToAction("Admin", new { filter = TempData["filter"]});
            }
        }

        [HttpPost]
        public IActionResult ResetPassword(int attorneyId)
        {
            _usersRepo.ResetPassword(attorneyId);
            TempData["ResetedPassword"] = true;
            return RedirectToAction(nameof(Admin), new { filter = TempData["filter"] });
        }
    }
}

LexinCorpApp/Views/Attorney/Admin.cshtml
@model AttorneyListViewModel
@{
    ViewData["Title"] = "Administración de usuarios";
}
<h2>Administración de usuarios</h2>
<form asp-action="Admin" method="get" asp-controller="Client">
    <label for="filter">Filtro de búsqueda:</label>
    <div class="input-group mb-3">
        <input type="text" class="form-control" name="filter" value="@Model.CurrentFilter" placeholder="Nombre del abogado, correo electrónico o cédula" aria-label="Nombre del usuario, correo electrónico o cédula" aria-describedby="button-addon2">
        <div class="input-group-append">
            <button class="btn btn-outline-info" type="submit" id="button-addon2">Buscar</button>
        </div>
    </div>
    <br />
</form>
@if (ViewBag.Updated ?? false)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <p>Abogado actualizado exitosamente!</p>

        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>

}
@if (ViewBag.ResetedPassword ?? false)
{
    <div class="alert alert-success alert-dismissible fade show">
        Clave de acceso del abogado reestablecida con éxito
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>

}
<div class="table-responsive">
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>Nombre del abogado</th>
                <th>Cédula</th>
                <th>Nombre de usuario</th>
                <th>Tipo de usuario</th>
                <th>Código de notario</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var attorney in Model.Attorneys)
            {
                <tr>
                    <td>@attorney.Name</td>
                    <td>@attorney.IdentificationNumber</td>
                    <td>@attorney.User.Username</td>
                    @if (attorney.User.IsAdmin)
                    {
                        @:<td>Administrador</td>
                    }
                    else
                    {
                        @:<td>Regular</td>
                    }
                    <td>@attorney.NotaryCode</td>
                    <td>

                        <form asp-action="Edit" asp-controller="Attorney" method="get" style="display:inline">
                            <input value="@attorney.Id" name="id" hidden />
                            <button type="submit" class="btn btn-primary" data-toggle="tooltip" data-placement="top" title="Editar">
                                <i class="fas fa-edit"></i>
                            </button>
                        </form>

                        <form asp-action="ResetPassword" asp-controller="Attorney" method="post" style="display:inline">
                            <input value="@attorney.Id" name="attorneyId" hidden />
                            <button type="submit" class="btn btn-primary" data-toggle="tooltip" data-placement="top" title="Restaurar contraseña">
                                <i class="fas fa-key"></i>
                            </button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div page-model="@Model.PagingInfo" page-action="Admin" page-classes-enabled="true"
     page-class="btn" page-class-normal="btn-outline-info"
     page-class-selected="btn-info" page-url-filter="@Model.CurrentFilter"
     page-number-url-key="pageNumber"
     class="btn-group float-right m-1">

</div>

LexinCorpApp/Views/Attorney/Edit.cshtml
@model NewAttorneyViewModel
@{
    ViewData["Title"] = "Editar usuario";
}
<script type="text/javascript">
    $(function () {
        $("#admissionDate").datepicker();
        $("#admissionDate").datepicker("option", "dateFormat", "dd/mm/yy");
        var date = new Date();
        var lastDay = new Date(date.getFullYear(), date.getMonth(), date.getDate());
        $("#admissionDate").datepicker("option", {
            maxDate: lastDay
        });
        var admission = @Html.Raw(Json.Serialize(Model.Attorney.AdmissionDate.ToString("dd/MM/yyyy")));
        $("#admissionDate").datepicker("setDate", admission);
        $("#passwordUser").val("");
    });
</script>
<h4>Actualización de abogado</h4>
<br />
@if (ViewBag.UpdatedAttorney ?? false)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <p>Información actualizada exitosamente!</p>

        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>

}
<form asp-action="Edit" asp-controller="Attorney" method="post" role="alert" id="@Model.Attorney.Id">
    @if (ViewData.ModelState.Any(x => x.Value.Errors.Any()))
    {
        <div class="alert alert-danger alert-dismissible fade show">
            @Html.ValidationSummary(false, "Errores de validación:")
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }
    <input asp-for="@Model.Attorney.Id" hidden />
    <input asp-for="@Model.Attorney.UserId" hidden />
    <input asp-for="@Model.Attorney.User.Id" hidden />
    <div class="form-row">
        <div class="form-group col-md-5">
            <label for="@Model.Attorney.Name">Nombre del abogado:*</label>
            <input type="text" asp-for="@Model.Attorney.Name" class="form-control" />
        </div>
        <div class="form-group col-md-2">
            <label for="@Model.Attorney.User.Username">Nombre de usuario:*</label>
            <input type="text" asp-for="@Model.Attorney.User.Username" class="form-control" required />
        </div>
        <div class="form-group col-md-3">
            <label for="@Model.Attorney.Alias">Alias:*</label>
            <input type="text" asp-for="@Model.Attorney.Alias" class="form-control" required />
        </div>
        <div class="form-group col-md-3">
            <label for="@Model.Attorney.User.Password">Contraseña:*</label>
            <input type="text" asp-for="@Model.Attorney.User.Password" id="passwordUser" class="form-control" />
        </div>
        <div class="form-group col-md-2">
            <label for="@Model.Attorney.User.IsAdmin">Tipo de usuario:*</label>
            <select class="form-control" asp-for="@Model.Attorney.User.IsAdmin">
                @if (Model.Attorney.User.IsAdmin == true)
                {
                    <option value="true" selected>Administrador</option>
                    <option value="false">Regular</option>
                }
                else
                {
                    <option value="true">Administrador</option>
                    <option value="false" selected>Regular</option>
                }
            </select>
        </div>

        <div class="form-group col-md-2">
            <label for="@Model.Attorney.AdmissionDate">Fecha de admisión:*</label>
            <input type="text" id="admissionDate" asp-for="@Model.Attorney.AdmissionDate" class="form-control" />
        </div>
        <div class="form-group col-md-3">
            <label for="@Model.Attorney.Address">Dirección:*</label>
            <input type="text" asp-for="@Model.Attorney.Address" class="form-control" required />
        </div>
        <div class="form-group col-md-3">
            <label for="@Model.Attorney.IdentificationNumber">Nº de identificación (cédula):*</label>
            <input type="text" asp-for="@Model.Attorney.IdentificationNumber" class="form-control" required />
        </div>
        <div class="form-group col-md-2">
            <label for="@Model.Attorney.AssignedPhoneNumber">Nº de teléfono asignado:*</label>
            <input type="tel" asp-for="@Model.Attorney.AssignedPhoneNumber" class="form-control" required />
        </div>
        <div class="form-group col-md-2">
            <label for="@Model.Attorney.PersonalPhoneNumber">Nº de teléfono personal:*</label>
            <input type="tel" asp-for="@Model.Attorney.PersonalPhoneNumber" class="form-control" required />
        </div>
        <div class="form-group col-md-3">
            <label for="@Model.Attorney.EmergencyContact">Contacto de emergencia:*</label>
            <input type="text" asp-for="@Model.Attorney.EmergencyContact" class="form-control" required />
        </div>
        <div class="form-group col-md-3">
            <label for="@Model.Attorney.EmergencyContactPhoneNumber">Nº de teléfono del contacto de emergencia:*</label>
            <input type="tel" asp-for="@Model.Attorney.EmergencyContactPhoneNumber" class="form-control" required />
        </div>
        <div class="form-group col-md-2">
            <label for="@Model.Attorney.NotaryCode">Código de notario:*</label>
            <input type="number" asp-for="@Model.Attorney.NotaryCode" class="form-control" required />
        </div>
        <div class="form-group col-md-2">
            <label for="@Model.Attorney.DepartmentId">Departamento:*</label>
            <select class="form-control" asp-for="@Model.Attorney.DepartmentId">
                @foreach (var d in Model.Departments)
                {
                    @if (@Model.Attorney.DepartmentId == d.DepartmentId)
                    {
                        @:<option value="@d.DepartmentId" selected>@d.Name</option>
                    }
                    else
                    {
                        @:<option value="@d.DepartmentId">@d.Name</option>
                    }

                }
            </select>
        </div>
        <div class="form-group col-md-3">
            <label for="@Model.Attorney.Email">Email:*</label>
            <input type="email" asp-for="@Model.Attorney.Email" class="form-control" required />
        </div>
        <div class="form-group col-md-3">
            <label for="Attorney_User_Active">Estado del usuario*:</label>
            <div class="form-check">
                <input class="form-check-input" type="radio" asp-for="@Model.Attorney.User.Active" value="true">
                <label class="form-check-label" for="Active">
                    Activo
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" asp-for="@Model.Attorney.User.Active" value="false">
                <label class="form-check-label" for="Active">
                    Inactivo
                </label>
            </div>
        </div>
        <div class="form-group col-md-5">
            <label>Permisos:</label>
            <div class="form-row">
                <div class="col-6">
                    <div class="form-check">
                        <input type="checkbox" asp-for="@Model.Attorney.CanApproveVacations" />
                        <label for="@Model.Attorney.CanApproveVacations">Aprobar vacaciones</label>
                    </div>
                    <div class="form-check">
                        <input type="checkbox" asp-for="@Model.Attorney.CanPreBill" />
                        <label for="@Model.Attorney.CanPreBill">Prefacturar</label>
                    </div>
                    <div class="form-check">
                        <input type="checkbox" asp-for="@Model.Attorney.CanBill" />
                        <label for="@Model.Attorney.CanBill">Facturar e Historial</label>
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-check">
                        <input type="checkbox" asp-for="@Model.Attorney.CanReviewBillDetail" />
                        <label for="@Model.Attorney.CanReviewBillDetail">Revisar detalle para facturar</label>
                    </div>
                    <div class="form-check">
                        <input type="checkbox" asp-for="@Model.Attorney.CanAdminDeposits" />
                        <label for="@Model.Attorney.CanAdminDeposits">Manejar abonos</label>
                    </div>
                </div>
            </div>

            
            


        </div>
    </div>

    <div class="form-row">
        <button type="submit" class="btn btn-primary">Actualizar</button>
    </div>
</form>